server:
  port: 8080

spring:
  application:
    name: gateway-auth-service

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 5s

  cloud:
    gateway:
      routes:
        - id: station-service-stations
          uri: http://localhost:8081
          predicates:
            - Path=/api/stations/**

        - id: station-service-attractions
          uri: http://localhost:8081
          predicates:
            - Path=/api/attractions/**

        - id: media-service-medias
          uri: http://localhost:8082
          predicates:
            - Path=/api/medias/**

jwt:
  secret: "change-me-change-me-change-me-change-me-very-secret-key-256"
  access-ttl-minutes: 15
  refresh-ttl-days: 30